# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-cont
          image: hello-world # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on
